### ISSUE TITLE
Unable to fetch postgress image

### ISSUE THREAD

**Issue by Shery11** [The-Great-Ape/server#3]
Hi i am trying to build this server code but it's failing as it is not able to fetch this image

![Screenshot 2021-06-16 at 2 54 29 AM](https://user-images.githubusercontent.com/21175010/122128742-7293ec80-ce4e-11eb-8e45-0bc2e247a73a.png)

Any idea how to resolve this?

One more thing in the .env file 

#POSTGRES DOCKER
POSTGRES_PASSWORD =
POSTGRES_DB = grape

I have this do we need to add a password as well?

**Comment by HRK44** [comment]
```
One more thing in the .env file

#POSTGRES DOCKER
POSTGRES_PASSWORD =
POSTGRES_DB = grape
```
this is for you local dev environment, you can put whatever you want as a password

For the image, idk what the issue would be since we are just pulling the default latest postgres image, maybe try by setting up a version like 13 instead of `latest`. See https://hub.docker.com/_/postgres

**Comment by Shery11** [comment]
So I need to have this postgress db running locally?

**Comment by grapemaster** [comment]
You will need to have Postgres running locally or remote using a SSH tunnel for the port you define, just replace your postgres password in the .env file

**Comment by bobthegrownup** [comment]
explained how to set it up
